# General

"Documentation":
  - "**/docs/**"
  - "**/README.md"

"Workflows":
  - ".github/workflows/**"

# Libraries

"API":
  - "api/**"

"Frontend":
  - "frontend/**"

"Scheduler":
  - "scheduler/**"

