name: "Api: Deploy"

defaults:
  run:
    working-directory: "api"

on:
  workflow_run:
    workflows: ["Api: Build"]
    types:
      - completed

concurrency:
  group: portainer-avaliu
  cancel-in-progress: false

jobs:
  deploy:
    name: "Deploy Image"
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    env:
      DOCKER_IMAGE_NAME: "joshlopes/ricardo-avaliacao-api"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Deploy the avaliu stack on Fiona
        uses: ./.github/actions/portainer-deploy
        with:
          stack-file: ${{ github.workspace }}/infrastructure/fiona.yaml
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          portainer-url: ${{ secrets.PORTAINER_URL }}
          portainer-token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          stack-id: ${{ secrets.PORTAINER_STACK_ID }}
          endpoint-id: ${{ secrets.PORTAINER_ENDPOINT_ID }}

      - name: 'Send message'
        uses: ./.github/actions/send-telegram-message
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD_ID }}
          message: |
            Validator Tools API APP deployed successfully!
            ${{ github.actor }}: ${{ github.event.commits[0].message }}
            
            **Changes**: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            **Deployment**: Portainer stack avaliu on Fiona
