name: "Api: Release please"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node
          package-name: 'API'
          path: 'api'
          tag-separator: '/'
          versioning-strategy: 'auto'
          tag-prefix: 'api-'
          create-release: true
