name: "Frontend: Release please"

defaults:
  run:
    working-directory: "frontend"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node
          path: 'frontend'
          manifest-file: 'frontend/package.json'
          include-component-in-tag: true
          skip-github-pull-request: false
          skip-github-release: false
